package com.vednex.business_suite.audit;

public enum AuditAction {
	COMPANY_REGISTERED,
	EMAIL_VERIFIED,
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGOUT,
	PASSWORD_RESET,
	COMPANY_UPDATED,
	USER_INVITED,
	INVITATION_ACCEPTED,
	ROLE_ASSIGNED,
	USER_DISABLED,
	TENANT_SWITCHED,
	REFRESH_TOKEN_REUSED
}
